### ISSUE TITLE
Issue on page /grundlagen.html

### ISSUE THREAD

**Issue by Ghazrilla** [JoergBitzer/Signalverarbeitung_Vorlesungsskript#22]
In Kapitel 4 werden ... und dem "Pol-Nullstellen-Diagram"... .
Es fehlt ein m für "Diagramm"

**Comment by AFExtract** [comment]
Fixed with https://github.com/JoergBitzer/Signalverarbeitung_Vorlesungsskript/commit/4ddb27d073479f5fda4e60f92773f6361fb74be7
